### ISSUE TITLE
Make the filters work

### ISSUE THREAD

**Issue by adirkandel** [Maakaf/maakaf-website#104]
1. Make the filters work.
2. Reflect the filters in the url query params so we can share a link with predefined filters for example.

**Comment by rotembarsela** [comment]
I'll take that when #74 will be resolved

**Comment by capyjayjay** [comment]
@adirkandel 
Hi! since Rotem did not take it since, I'm taking it, made it half way through.
Little question, I can see the mock data is set as array of objects - well we have two approaches to this the way I see it:

1. haveing the same structure as it is now, we set any filter to false as a default value, we set a state to contain the default value (array with objects) and gradually changing each filter isActive to true or false) 
2. We maintain a mock data as an array of strings (each string = filter), we aren't declartively saying isActive true / false, if the filter is within the selectedFIlters state, it is active and we can display it - otherwise, it isn't. We'd use the prelisted string array as a source of truth to validate the url params when ever a link is shared with predefined filters.

What is your take on this one?

**Comment by capyjayjay** [comment]
@adirkandel I commited some changes, I need your review for this, plus more clarification on what to do with the mock data or some explaination on how to handle it :)

**Comment by Darkmift** [comment]
I'm also interested in this one.
@RoyTennenbaum whats the status of this?

**Comment by Darkmift** [comment]
@eyallampel1 could you make a PR so we may review and integrate your work?
