### ISSUE TITLE
Home - Paths navigation links

### ISSUE THREAD

**Issue by rotembarsela** [Maakaf/maakaf-website#134]
### Relevant files:
Paths.tsx

* The anchor links are not working (navigating to home page), need to link them to the right pages

### Screenshots

![image](https://github.com/Maakaf/maakaf-website/assets/44998514/c62cd48b-9123-4510-a43a-79dcc1c4c7fa)

**Comment by eyallampel1** [comment]
I can see few issues was opened regarding links not being directed to the right places .
As previously discussed, I understand your preference is for a single pull request to address all these link-related issues.
If that's still the case, I'd like to take on this task and ensure all links function as expected.

Please confirm, and assign me ,and I'll proceed with the necessary corrections.

**Comment by rotembarsela** [comment]
> I can see few issues was opened regarding links not being directed to the right places . As previously discussed, I understand your preference is for a single pull request to address all these link-related issues. If that's still the case, I'd like to take on this task and ensure all links function as expected.
> 
> Please confirm, and assign me ,and I'll proceed with the necessary corrections. However, if @rotembarsela is interested in handling this, please go ahead. I wasn't certain If he wants to be assigned to this issue or just opened it .

I separated the Issues because they are on different components, you are welcome to take them, I just found that as a bug and opened the issues 🙂

**Comment by Drorka** [comment]
@rotembarsela @eyallampel1 
I too think it makes sense to take care of all the links that currently aren't working, instead of opening several issues and PRs for 2-3 links at a time.

@eyallampel1 note here, that this issues is still not a part of a project, and doesn't have a status (backlog / ready for dev etc.).
So I would let the maintainers know about this issue and see if they approve it, or want to make any changes to it.

**Comment by Darkmift** [comment]
fixed as part of #144 pendine review @UrielOfir @RoyTennenbaum @rotembarsela
